services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:9
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chat_app
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
